# Generated by Django 5.1.3 on 2024-11-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramètres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CINETPAY_APIKEY', models.CharField(blank=True, max_length=255, null=True)),
                ('CINETPAY_SECRETE_KEY', models.CharField(blank=True, max_length=255, null=True)),
                ('CINETPAY_SITE_ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
