# Generated by Django 5.1.3 on 2024-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsite', '0002_paramètres'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
