# Generated by Django 5.1.3 on 2024-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monsite', '0003_profilutilisateur_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveau',
            name='duree',
            field=models.IntegerField(default=30),
        ),
    ]
